add fog piece, remove some chess checks
ak47andrew/Fog-of-war pull request #1
Opened 2024-11-04 18:33 UTC by JiriH94

Hey,  some possible inspiration, it's not fully done and had to comment out the tests etc. if I'll find time I can continue on some changes, but I am not sure what direction you want to take :)

2024-11-04 18:58 UTC, ak47andrew requested changes

2024-11-04 18:58 UTC, ak47andrew commented on Chess-Challenge/resources/Pieces.png
1. Change question mark with something more suitable (chess.com style for example)
2. Also it's shifted for whatever reason
![Screenshot_20241104_214718](https://github.com/user-attachments/assets/fccb1a87-69a2-4d2d-a4a1-c233ba953d0e)

2024-11-04 18:58 UTC, ak47andrew commented on Chess-Challenge/src/API/Board.cs
Remove ForceSkipTurn bc it's no longer needed after SkipTurn

2024-11-04 18:58 UTC, ak47andrew commented on Chess-Challenge/src/Framework/Application/Helpers/Tester.cs
It's just deeply funny to me that you commented out this file completely. Not required, but better to add some

2024-11-04 18:58 UTC, ak47andrew commented on Chess-Challenge/src/Framework/Chess/Move Generation/MoveGenerator.cs
I don't know why, but checks and stalemate is still a thing. Here's some test fens that should be run with MyBot and will raise IndexError:
`3k4/3r3p/p1p4b/3pp1p1/n7/8/2b5/K1n5 w - - 4 79`
`8/8/3nb3/1p1p1p2/p7/1rpk4/3r4/2K4n w - - 6 151`
`5k2/2b2n1r/8/5p2/1p2p3/p7/1r6/K7 w - - 4 101`

2024-11-04 19:14 UTC, JiriH94 commented on Chess-Challenge/src/API/Board.cs
deleted, also made the SkipTurn return void

2024-11-05 18:56 UTC, ak47andrew commented on Chess-Challenge/src/Framework/Chess/Move Generation/MoveGenerator.cs
Waiting for this one to continue working on a project. Probably will submit pull request on this issue or so, but not really sure

2024-11-09 16:45 UTC, JiriH94 commented on Chess-Challenge/src/Framework/Chess/Move Generation/MoveGenerator.cs
should be fixed now

2024-11-10 15:35 UTC, ak47andrew approved these changes
Sounds good to me! Haven't checked everything yet, but a quick inspection is done.
Merge, thanks for a big chunk of work done!

2024-11-10 15:35 UTC, merged